#!/bin/sh
# /etc/uci-defaults/98_network_custom_setting

set -eu

find_anon_by_opt() {
  local pkg="$1" type="$2" opt="$3" val="$4"
  uci -q show "$pkg" | sed -n "s/^${pkg}\.\(@${type}\[[0-9]\+\]\)\.${opt}='${val}'$/\1/p" | head -n1
}


uci -q delete dhcp.meshif 2>/dev/null || true
uci -q set dhcp.meshif='dhcp'
uci -q set dhcp.meshif.interface='meshif'
uci -q set dhcp.meshif.start='50'
uci -q set dhcp.meshif.limit='150'
uci -q set dhcp.meshif.leasetime='6h'
uci -q set dhcp.meshif.ra='server'
uci -q commit dhcp



uci -q delete network.bat0 2>/dev/null || true
uci -q set network.bat0='interface'
uci -q set network.bat0.proto='batadv'
uci -q set network.bat0.routing_algo='BATMAN_IV'
uci -q set network.bat0.aggregated_ogms='1'
uci -q set network.bat0.ap_isolation='0'
uci -q set network.bat0.bonding='0'
uci -q set network.bat0.bridge_loop_avoidance='1'
uci -q set network.bat0.distributed_arp_table='1'
uci -q set network.bat0.fragmentation='1'
uci -q set network.bat0.network_coding='0'
uci -q set network.bat0.orig_interval='1000'
uci -q set network.bat0.gw_mode='server'
uci -q set network.bat0.gw_bandwidth='10000/2000'
uci -q set network.bat0.hop_penalty='25'
uci -q set network.bat0.isolation_mark='0x00000000/0x00000000'
uci -q set network.bat0.log_level='0'
uci -q set network.bat0.multicast_mode='1'
uci -q set network.bat0.multicast_fanout='16'


uci -q delete network.mesh 2>/dev/null || true
uci -q set network.mesh='interface'
uci -q set network.mesh.proto='batadv_hardif'
uci -q set network.mesh.master='bat0'
uci -q set network.mesh.mtu='1536'


brmesh="$(find_anon_by_opt network device name br-meshif || true)"
if [ -z "${brmesh:-}" ]; then
  brmesh="$(uci -q add network device)"
fi
uci -q set network."$brmesh".name='br-meshif'
uci -q set network."$brmesh".type='bridge'
uci -q delete network."$brmesh".ports 2>/dev/null || true
uci -q add_list network."$brmesh".ports='bat0'


uci -q delete network.meshif 2>/dev/null || true
uci -q set network.meshif='interface'
uci -q set network.meshif.device='br-meshif'
uci -q set network.meshif.proto='static'
uci -q set network.meshif.ipaddr='192.168.100.2'
uci -q set network.meshif.netmask='255.255.255.0'
uci -q delete network.meshif.dns 2>/dev/null || true
uci -q add_list network.meshif.dns='1.1.1.1'
uci -q add_list network.meshif.dns='203.237.32.100'
uci -q set network.meshif.ipv6='1'

uci -q commit network


[ -f /etc/config/wireless ] || wifi config
uci -q set wireless.radio0.disabled='0'
uci -q delete wireless.default_radio0 2>/dev/null || true
uci -q delete wireless.wmesh 2>/dev/null || true
uci -q set wireless.wmesh='wifi-iface'
uci -q set wireless.wmesh.device='radio0'
uci -q set wireless.wmesh.network='mesh'
uci -q set wireless.wmesh.mode='mesh'
uci -q set wireless.wmesh.mesh_id='Network_Id'
uci -q set wireless.wmesh.encryption='psk2+aes'
uci -q set wireless.wmesh.key='Network_PW'
uci -q set wireless.wmesh.mcast_rate='24000'
uci -q set wireless.wmesh.mesh_fwding='0'
uci -q set wireless.wmesh.mesh_ttl='1'
uci -q set wireless.wmesh.disabled='0'
uci -q commit wireless


z="$(find_anon_by_opt firewall zone name meshif || true)"
if [ -z "${z:-}" ]; then
  z="$(uci -q add firewall zone)"
fi
uci -q set firewall."$z".name='meshif'
uci -q delete firewall."$z".network 2>/dev/null || true
uci -q add_list firewall."$z".network='meshif'
uci -q set firewall."$z".input='ACCEPT'
uci -q set firewall."$z".output='ACCEPT'
uci -q set firewall."$z".forward='ACCEPT'


f="$(uci -q add firewall forwarding)"
uci -q set firewall."$f".src='meshif'
uci -q set firewall."$f".dest='wan'


w="$(find_anon_by_opt firewall zone name wan || true)"
if [ -n "${w:-}" ]; then
  uci -q set firewall."$w".input='ACCEPT'
  uci -q set firewall."$w".forward='ACCEPT'
fi

uci -q commit firewall

exit 0
